### ISSUE TITLE
Implement camera-to-cloud picture sending

### ISSUE THREAD

**Issue by BoldizarF** [BoldizarF/ariot19#13]

**Comment by ddjohn** [comment]
Take a picture:
> $ **fswebcam input.jpg**

To take a picture and base64 encode in one line:
> $ **fswebcam - | base64**

To take a picture, base64 it and restapi it in one line:
> $ **curl -X POST  http://_someip_:_someport_/restapi -d pic=$(fswebcam - | base64)**

**Comment by ddjohn** [comment]
Implemented here:
https://github.com/BoldizarF/ariot19/tree/master/camtocloud
