### ISSUE TITLE
Prepare audio files for attack behaviour

### ISSUE THREAD

**Issue by BoldizarF** [BoldizarF/ariot19#20]

**Comment by lexious89** [comment]
[ariot_dog_barking.zip](https://github.com/BoldizarF/ariot19/files/2910602/ariot_dog_barking.zip)
[Uploading itt.zip…]()
[Uploading sspblobbs.zip…]()

**Comment by lexious89** [comment]
[ariot_dog_barking.zip](https://github.com/BoldizarF/ariot19/files/2910605/ariot_dog_barking.zip)

**Comment by lexious89** [comment]
aplay -D hw:0,0 -r 48000 -f S32_LE ariot_dog_barking.wav. 
Device (-D) needs to be checked with alsa devices in raspberry pie.

**Comment by platisd** [comment]
If this doesn't work, you could always try to bring the dog along to the competition. :1st_place_medal:

**Comment by lexious89** [comment]
Haha and a small stick to trigger the barking..

**Comment by platisd** [comment]
lol! :laughing:

**Comment by spukki01** [comment]
Done!
