### ISSUE TITLE
WIN ARIOT

### ISSUE THREAD

**Issue by platisd** [BoldizarF/ariot19#30]
### ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿

**Comment by platisd** [comment]
Best of luck tomorrow!

**Comment by BoldizarF** [comment]
No pressure :D

**Comment by platisd** [comment]
With 23 badges, you won my :heart:
